/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ColorSwatches: typeof import('./src/components/ColorSwatches.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    FormDrawer: typeof import('./src/components/FormDrawer.vue')['default']
    HotkeysHelp: typeof import('./src/components/HotkeysHelp.vue')['default']
    IconPicker: typeof import('./src/components/IconPicker.vue')['default']
    PagePlaceholder: typeof import('./src/components/PagePlaceholder.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionCard: typeof import('./src/components/SectionCard.vue')['default']
    SettingsGroup: typeof import('./src/components/SettingsGroup.vue')['default']
  }
}
